### ISSUE TITLE
2 VMs in one post request

### ISSUE THREAD

**Issue by Outek** [vmkdaily/vFlux-Stats-Kit#11]
```PowerShell
VERBOSE: POST http://<Servername>:7003/write?db=esx with -1-byte payload
WARNING: Problem writing object to InfluxDB!
WARNING: The remote server returned an error: (400) Bad Request.
Invoke-RestMethod : {"error":"unable to parse 'cpu.ready.summation,host=<vmname1>
<vmname2>,instance=0,interval=20,type=VM,unit=millisecond,vc=<vcentername> value=0.1 1538482182880123904': invalid boolean"}
At C:\Program Files\WindowsPowerShell\Modules\Fluxor\public\Write-FluxCompute.ps1:226 char:24
+             $result = (Invoke-RestMethod @sParamRest)
+                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
```

Any idea why ther are 2 vms in one iwr call? I think this should be only 1 vm per post request, right?

**Comment by vmkdaily** [comment]
Thanks! That is interesting. The field in question is `[string]` not `[string[]]`, so should not be capable of presenting an array upstream.  I cannot reproduce so far, but I am familiar with the error message.

The error is the common response when the line protocol was not proper (for example line breaks in the wrong place, or missing quotes, etc). 

When reviewing the output of `Get-FluxCompute`, do you see the same (or any) issues with the outputted line protocol format?

**Comment by Outek** [comment]
I'm not sure, where this is coming from. I didn't had the time to look at it today. 
Maybe this two VMs are cloned from one to the other and they have the same GUID, could this be a problem?

**Comment by vmkdaily** [comment]
The virtual machine Id is unique to a vCenter.  Connecting to only one vCenter when gathering stats may help for now until handling is added.

**Comment by vmkdaily** [comment]
Also the message says you are trying to write to a db named `esx ` (should be `compute` if following examples) but guessing that is just redacting. See next comment for resolution. Thanks!

**Comment by vmkdaily** [comment]
The `Fluxor `module has been updated to version `1.0.0.3` and your issue should be resolved! We now perform `Get-VM` and `Get-VMHost` only against the `$Global:DefaultVIServer` . Thanks!
