### ISSUE TITLE
error":"unable to parse 

### ISSUE THREAD

**Issue by linuxmonkey** [vmkdaily/vFlux-Stats-Kit#12]
Hi
I get error":"unable to parse when i will write stats with write-fluxIOPS or write-FluxCompute to the database. The problem is in the get-FluxIOPS and get-FluxCompute:

When the script iteral trough the stats and get the name for the EntityID: 

[string]$name = ($VMs | Where-Object {$_.Id -match $vmstat.EntityId} | Select-Object -ExpandProperty Name) -replace ' ',$DisplayNameSpacer

With "-match" it can be the situation: VirtualMachine-1 matches also with VirtualMachine-11..12.. 
use -eq instad of -match will solve the problem.

**Comment by vmkdaily** [comment]
Thanks! Perfectly stated! The module has been updated to version `1.0.0.7` to resolve this issue.
