### ISSUE TITLE
Error 400 with Invoke-vFluxCompute.ps1

### ISSUE THREAD

**Issue by rogersa2k** [vmkdaily/vFlux-Stats-Kit#7]
I just tried to set up the new REST based stuff and this is what I am getting:
`WARNING: Problem writing cpu.usagemhz.average for myhost at 11/17/2017 9:48:54 AM`
`WARNING: The remote server returned an error: (400) Bad Request.`

I have been using the older curl version for a year with no issues.

Thanks!
- Aaron

**Comment by vmkdaily** [comment]
Thanks for the feedback! I'm happy to hear you've been running reliably until now.  Not so happy to hear the REST version is not working for you.

**Questions:**
Feel free to answer any that are relevant..
1. Does this happen with the REST based IOPS scripts too or just the Compute?
2. Did anything else change such as version of InfluxDB?
3. What OS are you running on (i.e. 2012 R2, etc.)
4. What version of PowerShell and PowerCLI

**Legacy Support for Old InfluxDB Versions:**
The REST technique is supported on the very oldest versions of InfluxDB so there is no need to upgrade or use the latest InfluxDB (unless you want to of course). Not sure if you are, but worth mentioning in case you are making multiple changes at once.

**Recommendations:**
Snapshot first - Always take a vSphere snapshot (or get a good backup) before performing maintenance.

**Actions:**
1. Fully Windows Update for all Important and Critical
2. Update PowerShell to 5.1
3. Upgrade PowerCLI to latest (i.e. 6.5.4)
4. Ensure Windows Firewall allows communication (if across devices)

**Optional Actions:**
A. Create a test InfluxDB database
B. Attempt to push data using the Influx scripts
C. Review the admin Web Interface for InfluxDB if available.
D. Review logs on InfluxDB
E. Optionally try and write line commands to InfluxDB using Invoke-RestMethod manually.

**Recommended Editors:**
If the script has been copied around across editors or cultures, consider reviewing with a strict editor such as Microsoft ISE (with Steroids), VSCode, etc.

**Next Steps**
I'd be interested to hear more.  Feel free to respond with any of the points that are of interest to you. 
 Hopefully I can help but I have not seen this one!

-Mike

**Comment by rogersa2k** [comment]
Thanks for getting back to me! Unfortunately with the Thanksgiving holiday
I won't be able to do much until next week at the earliest. I'll do my best
to gather all the info you requested & do some more
testing/troubleshooting.

- Aaron Rogers

**Comment by DrDrrae** [comment]
Getting the same issue.  Here's hopefully a little more information that can help figure out what's going on.

```
VERBOSE: 
VERBOSE: Measurement: net.usage.average
VERBOSE: Value: 301
VERBOSE: Name: 10.63.81.11
VERBOSE: Unix Timestamp: 1511362638322864896
VERBOSE: POST http://grafana.redacted.com:8086/write?db=compute with -1-byte payload
WARNING: Problem writing net.usage.average for  at 11/22/2017 9:57:18 AM
WARNING: The remote server returned an error: (400) Bad Request.
Invoke-RestMethod : {"error":"unable to parse 'net.usage.average,host=10.63.81.11,type=VMHost,vc=vcenter.redacted.com,cluster=redacted 
Cluster,unit=KBps,interval=20,instance=vmnic3 value=0 1511362638385363712': invalid boolean"}

At C:\Program Files\vFlux-Stats-Kit\Invoke-vFluxCompute.ps1:316 char:17
+ ...       $rm = Invoke-RestMethod -Headers @{Authorization=$authheader} - ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
```

**Comment by DrDrrae** [comment]
Looking further at it, I think it has to do with the cluster having a space in the name.  If I run a query manually removing the space, it works.

```
$authheader = "Basic " + ([Convert]::ToBase64String([System.Text.encoding]::ASCII.GetBytes("username:password")))
$uri = 'http://grafana.redacted.com:8086/write?db=compute'
$postParams = "net.usage.average,host=10.63.81.11,type=VMHost,vc=vcenter.redacted.com,cluster=Redacted_Cluster,unit=KBps,interval=20,instance=vmnic3 value=0 1511363377986402048"
Invoke-RestMethod -Headers @{Authorization = $authheader} -Uri $uri -Method POST -Body $postParams
```

**Comment by rogersa2k** [comment]
Oh, of course, the spaces! That's almost definitely it. I had to modify the
older scripts to handle that. Thanks for the heads up.

- Aaron

**Comment by rogersa2k** [comment]
Yep, this was it. Previously I added a couple replace statements to escape
spaces or commas in our cluster names.

$cluster = $vm.VMHost.Parent
$cluster = $cluster -Replace ' ', '\ '
$cluster = $cluster -Replace ',', '\,'

- Aaron

**Comment by vmkdaily** [comment]
Ahh the spaces on VM/cluster names. I'm glad it's an easy one (and thanks to all for catching/sharing). I do have it coded and running fine in my lab, but for now folks just have to account for this themselves.  I will get this added to the next version for sure (support for spaces in cluster and virtual machine name).

**Comment by vmkdaily** [comment]
FYI - the scripts have been updated.  Thanks!
