### ISSUE TITLE
Problem writing cpu.usage.average

### ISSUE THREAD

**Issue by AlexPetersen** [vmkdaily/vFlux-Stats-Kit#8]
Hi Mike,

I'm having some problems getting data on my ESXi hosts with your script, most of the stats return a 400 error when posting it to the influx database, see excerpts below:

**This one fails...**
VERBOSE: Measurement: cpu.usage.average
VERBOSE: Value: 0,64
VERBOSE: Name: esxi01.int.hjemmelab.dk
VERBOSE: Unix Timestamp: 1515358503329777664
VERBOSE: POST http://192.168.168.37:8086/write?db=telegraf with -1-byte payload
WARNING: Problem writing cpu.usage.average for  at 07-01-2018 21:55:03
WARNING: The remote server returned an error: (400) Bad Request.
**... while this one succeeds**
VERBOSE:
VERBOSE: Measurement: cpu.usage.average
VERBOSE: Value: 1,22
VERBOSE: Name: esxi01.int.hjemmelab.dk
VERBOSE: Unix Timestamp: 1515358503356783104
VERBOSE: POST http://192.168.168.37:8086/write?db=telegraf with -1-byte payload
VERBOSE: received -1-byte response of content type application/json

Similar story with net.usage.average:

**This one succeeds...**
VERBOSE: Measurement: net.usage.average
VERBOSE: Value: 0
VERBOSE: Name: esxi01.int.hjemmelab.dk
VERBOSE: Unix Timestamp: 1515358503527790336
VERBOSE: POST http://192.168.168.37:8086/write?db=telegraf with -1-byte payload
VERBOSE: received -1-byte response of content type application/json
**... while this one fails**
VERBOSE:
VERBOSE: Measurement: net.usage.average
VERBOSE: Value: 0
VERBOSE: Name: esxi01.int.hjemmelab.dk
VERBOSE: Unix Timestamp: 1515358503556796416
VERBOSE: POST http://192.168.168.37:8086/write?db=telegraf with -1-byte payload
WARNING: Problem writing mem.usage.average for  at 07-01-2018 21:55:03
WARNING: The remote server returned an error: (400) Bad Request.

Best regards,
Alex

**Comment by vmkdaily** [comment]
Thanks for sharing! We may need more information from the InfluxDB logs or perhaps debugging enabled on your PowerShell session. From the script's perspective it is trapping the error, but I don't go any further than that (perhaps I should add a cmdlet or parameter for troubleshooting only).

Please ensure that the devices you are testing have an uptime of 1 hour minimum.  You can also refine what you are testing against by modifying the script and choosing a single virtual machine or ESXi host if desired.

This could be something with session handling with REST too as some of your writes are successful, and some are not.  I'm not sure how to troubleshoot that, but there is an open issue with some code examples to resolve same at https://github.com/vmkdaily/vFlux-Stats-Kit/issues/6.

**Comment by ghost** [comment]
Hello Mike,

just want to tell you that I got exactly the same problem like Alex.
I tried to use your scripts in the following environment:

Scripts run on Win2k16 Server with powershell v5
Influxdb (v1.3.6) runs on CentOS 7
ESXi and VCSA are at 6.5

I also tried the workaround at [#6](https://github.com/vmkdaily/vFlux-Stats-Kit/issues/6) without success.
Is there any way to get this fixed?

Best regards
MikeWee

**Comment by vmkdaily** [comment]
Excellent! Thanks for the detailed version information. I wonder if you can reproduce with your InfluxDB running on Windows.  I will test these out soon either way.

My current favorite has been all Windows for everything using the vendor provided binaries.  I need to ramp up my CentOS testing though, as there is some cool stuff happening soon with PowerCLI and PowerShell Core 6.0, which I also need to start working on.

**Comment by ghost** [comment]
Hello again,

sorry but I dont have a windows machine atm for testing, But I attached the logs from the powershell output and the influxdb. I hope it helps you a bit with debugging.

There is another strange thing I noticed, even the successfull queries  (204 0) doesnt show up in the database.

[influxdb.log](https://github.com/vmkdaily/vFlux-Stats-Kit/files/1647203/influxdb.log)
[Invoke-vFluxCompute.log](https://github.com/vmkdaily/vFlux-Stats-Kit/files/1647204/Invoke-vFluxCompute.log)

If you need any other information just tell me, I really hope to get this running.

Best regards
MikeWee

**Comment by vmkdaily** [comment]
Could this have something to do with cultures across devices? I notice your numbers are `0,64` (fictional example) where an **en-us** culture on the other device would be expecting `0.64`. Cultures can be controlled in PowerShell, not sure about on CentOS. Just an idea anyway.  Also of course, make sure firewall is good on both devices.

**Comment by vmkdaily** [comment]
Unrelated to your issue, but I just fixed the warning message so at least it shows the ESXi host name having problems writing to InfluxDB.  This won't show us anything new, since we already see your host is valid from the verbose logs. This just makes the line that says 'problem writing [measurement] for [esx name] at [date]' look as expected.

**Comment by AlexPetersen** [comment]
Sorry for the late reply, been busy.

my setup is almost exactly the same as MikeWee, except my influx is a newer version and on Ubuntu.

Scripts run on Win2k16 Server with powershell v5
Influxdb (v1.4.2) on Ubuntu Server 16.04.3 LTS
ESXi and VCSA are at 6.5 (latest patch)

I'll try running it again, and see if I can get any new info.

**Comment by AlexPetersen** [comment]
[Invoke-vFluxCompute-log-20jan2018.log](https://github.com/vmkdaily/vFlux-Stats-Kit/files/1648936/Invoke-vFluxCompute-log-20jan2018.log)
Attached the log, the error it throws is this:

> TerminatingError(Invoke-RestMethod): "{"error":"unable to parse 'cpu.usage.average,host=esxi03.int.hjemmelab.dk,type=VMHost,vc=vcenter.int.hjemmelab.dk,cluster=HL-Cluster01,unit=%,interval=20,instance=6 value=1,59 1516462872558100736': invalid field format"}
"

**Comment by ghost** [comment]
Hello@all,

also debugged the script the last days, I got the same error code like Alex.
Maybe I am wrong but I take a look at the "InfluxDB API reference" and saw in the examples that floatingpoint values are seperated by dot and not by comma.

So what would be the best solution to fix this? (if possible)

Best regards
MikeWee

**Comment by vmkdaily** [comment]
I think the issue is related to PowerShell culture.  Try switching to 'en-Us'. You can do `Get-Culture` to review your current settings.

Last night I deployed the latest CentOS7, InfluxDB and Grafana and all is working perfectly. I followed my really old guide at http://vmkdaily.ghost.io/influxdb-and-grafana-on-centos/ which still works fine for getting the latest versions and configuring the firewall on CentOS.

Unfortunately though, I cannot reproduce this issue; I am in the US region where we natively use dot for floating point. I hope that I can be more help. Please let me know how things go!

**Comment by ghost** [comment]
Hello Mike,

just checked the culture in powershell again, that was the issue!
Now everything runs smoothly.

thanks for your help.

Best regards
MikeWee

**Comment by vmkdaily** [comment]
That's great news!  It's an honor to have such great participation so thank you both!

**Comment by vmkdaily** [comment]
I'll keep this issue open so folks are aware that InfluxDB prefers a PowerShell culture of en-US.  Perhaps I can add some handling in the scripts.

**Comment by vmkdaily** [comment]
Closing this old issue; resolved since becoming Fluxor module.
